# Check if code-server is running
systemctl status code-server@coder

# Check if journalctl is giving us logs, and if something failed
journalctl -u code-server@coder

# If journalctl isn't giving logs:
systemd restart systemd-journald 
# or
sed -i.bak 's/#Storage=auto/Storage=persistent/' /etc/systemd/journald.conf
mkdir -p /var/log/journal
systemctl force-reload systemd-journald
systemctl restart systemd-journald
# then, if needed:
sudo reboot
